# Setup
title:               NI-JEY
tagline:             'the technical blog'
description:         'A technical blog about Java, Spring, and software engineering.'
url:                 https://nijeysh.github.io/
baseurl:             ''
paginate:            6
permalink:           pretty

# About/contact
author:
  name:              Yejin Shin
  url:               https://github.com/nijeysh
  email:             yejin6521@naver.com
  github:            nijeysh

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

tech_submenu:
  - title: "Java"
    url: "/tech/java/"
    category: "java"
  - title: "Spring"
    url: "/tech/spring/"
    category: "spring"
  - title: "Python"
    url: "/tech/python/"
    category: "python"
  - title: "Database"
    url: "/tech/database/"
    category: "database"
  - title: "Docker"
    url: "/tech/docker/"
    category: "docker"
  - title: "Kubernetes"
    url: "/tech/kubernetes/"
    category: "kubernetes"
